<?php
/**
 * Development router that mirrors the project's .htaccess rewrite rules,
 * so the PHP built-in server behaves like Apache mod_rewrite.
 *
 * Usage:
 *     php -S 127.0.0.1:8000 tools/dev-router.php
 *
 * The router resolves the request to a real file and then points
 * SCRIPT_NAME / SCRIPT_FILENAME at that file — exactly what Apache does
 * after an internal rewrite — so the application's base-path detection
 * and language-prefix logic behave identically to production.
 */

$root = dirname(__DIR__);   // project root (this file lives in /tools)
$uri  = parse_url($_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH) ?? '/';
$uri  = '/' . ltrim(rawurldecode($uri), '/');
$path = ltrim($uri, '/');

/* Apache matches an *optional single* trailing slash — `^(en|ar)/(.+?)/?$`
   and `^([^/]+?)/?$` in .htaccess — so /en/contact/ resolves exactly like
   /en/contact. Do the same here (one slash only, so `//` still 404s the way
   it does in production). REQUEST_URI keeps the slash, so the application's
   canonical-redirect logic still sees the address the visitor typed. */
if ($path !== '' && str_ends_with($path, '/') && !str_ends_with($path, '//')) {
    $path = substr($path, 0, -1);
}

/** Serve a resolved .php file the way Apache would after a rewrite. */
$serve = static function (string $file, string $urlPath) use ($root): bool {
    if (!is_file($file) || !str_ends_with($file, '.php')) {
        return false;
    }
    // Mirror Apache: SCRIPT_NAME/FILENAME describe the file being executed,
    // while REQUEST_URI keeps the address the visitor typed.
    $_SERVER['SCRIPT_NAME']     = '/' . ltrim($urlPath, '/');
    $_SERVER['SCRIPT_FILENAME'] = $file;
    $_SERVER['PHP_SELF']        = $_SERVER['SCRIPT_NAME'];
    require $file;
    return true;
};

// --- 1. A real, directly requested file (assets, actions, ...) — serve it.
$direct = $root . str_replace('/', DIRECTORY_SEPARATOR, $uri);
if ($uri !== '/' && is_file($direct)) {
    if (str_ends_with($direct, '.php')) {
        return $serve($direct, $uri);
    }
    return false;   // let the built-in server stream static assets
}

// --- 2. /sitemap.xml and /robots.txt are generated by PHP.
if ($path === 'sitemap.xml' || preg_match('#^(en|ar)/sitemap\.xml$#', $path)) {
    return $serve($root . '/sitemap.php', $path);
}
if ($path === 'robots.txt' || preg_match('#^(en|ar)/robots\.txt$#', $path)) {
    return $serve($root . '/robots.php', $path);
}

// --- 3. Language-prefixed URLs: /en/... and /ar/...
if (preg_match('#^(en|ar)(?:/(.*))?$#', $path, $m)) {
    $rest = $m[2] ?? '';
    if ($rest === '') {
        return $serve($root . '/index.php', 'index.php');
    }
    $candidate = $root . '/' . str_replace('/', DIRECTORY_SEPARATOR, $rest);
    if (is_file($candidate) && str_ends_with($candidate, '.php')) {
        return $serve($candidate, $rest);
    }
    if (is_file($candidate . '.php')) {
        return $serve($candidate . '.php', $rest . '.php');
    }
    http_response_code(404);
    return $serve($root . '/404.php', '404.php');
}

// --- 4. Extension-less URLs: /about -> /about.php, /services/x -> .php
$candidate = $root . '/' . str_replace('/', DIRECTORY_SEPARATOR, $path);
if (is_file($candidate) && str_ends_with($candidate, '.php')) {
    return $serve($candidate, $path);
}
if (is_file($candidate . '.php')) {
    return $serve($candidate . '.php', $path . '.php');
}

// --- 5. Home.
if ($path === '') {
    return $serve($root . '/index.php', 'index.php');
}

// --- 6. Nothing matched.
http_response_code(404);
return $serve($root . '/404.php', '404.php');